решение 1й задачи 1го занятия (sortStrings)
js-tasks-ru/js-20200928_vladykod pull request #2
Opened 2020-10-05 16:28 UTC by VladykoD

2020-10-05 16:41 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
pick
- should return new object with one passed field
- should return new object with a few passed field
- should return an empty object if passed fields does not found
```
```diff
omit
- should return a new object without passed field
- should return a new object without few passed fields
- should return initial object if passed fields doesn't found
```

2020-10-05 16:48 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
pick
- should return new object with one passed field
- should return new object with a few passed field
- should return an empty object if passed fields does not found
```
```diff
omit
- should return a new object without passed field
- should return a new object without few passed fields
- should return initial object if passed fields doesn't found
```

2020-10-06 13:57 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.html
> +<!DOCTYPE html>
этих изменений не должно быть в PR, нужно убрать

2020-10-06 13:59 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  const enLang = ['65', '122'];
пожалуйста перечитайте главу из учебнику посвященную сортировке строк (в задачнике есть ссылка) и пересмотрите разбор домашек на занятии. После исправте решение `sortStrings`

2020-10-06 13:59 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2020-10-08 00:33 UTC, VladykoD commented on 02-javascript-data-types/1-sort-strings/index.html
> +<!DOCTYPE html>
да, я уберу. 
Я думала PR удалился из-за проваленных тестов и сильно не парилась. 

Спасибо, что уделили время.

2020-10-08 01:07 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-10-08 01:14 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
createGetter
- should return existed properties
- should return "undefined" for properties which does not exist
- gets obj.property
- returns undefined for no property
- gets obj.nested.property
- returns undefined for no nested.property
- gets more.nested.property
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
trimSymbols
- should remove an identical consecutive characters that exceed the specified size
- should return empty string if it was passed to function like an argument
- should return empty string if "size" equal 0
- should return the same string if "size" parameter wasn't specified
```
```diff
invertObj
+ should return "undefined" if object wasn't passed
- should swap keys and values and return new object
- should return empty object if was passed object without values
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```
```diff
uniq
- should return array with uniq values
- should return empty array if was passed array without values
- should return empty array if arguments wasn't passed
```

2020-10-08 04:38 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
createGetter
- should return existed properties
- should return "undefined" for properties which does not exist
- gets obj.property
- returns undefined for no property
- gets obj.nested.property
- returns undefined for no nested.property
- gets more.nested.property
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
trimSymbols
+ should remove an identical consecutive characters that exceed the specified size
+ should return empty string if it was passed to function like an argument
+ should return empty string if "size" equal 0
+ should return the same string if "size" parameter wasn't specified
```
```diff
invertObj
+ should swap keys and values and return new object
+ should return empty object if was passed object without values
+ should return "undefined" if object wasn't passed
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```
```diff
uniq
+ should return array with uniq values
+ should return empty array if was passed array without values
+ should return empty array if arguments wasn't passed
```

2020-10-08 23:04 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-09 19:55 UTC, dosandk approved these changes
good 👍

2020-10-09 19:56 UTC, merged